/**
 * `notFound()` from the room route.
 *
 * Two things land here and they want the same answer: a code with a typo in it,
 * and a code for a room that was deleted or had its code regenerated by the host
 * (§11.3). The copy leads with the likelier one and names the characters that
 * are not in the alphabet, because "O instead of 0" is the mistake people
 * actually make — and the alphabet contains neither, so we can say so plainly.
 */
import Link from 'next/link';
import { SearchX } from 'lucide-react';
import { ROOM_CODE_LENGTH } from '@syncstudy/shared';
import { buttonVariants } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Logo } from '@/components/ui/logo';

export default function RoomNotFound() {
  return (
    <div className="flex min-h-dvh flex-col">
      <header className="flex h-12 shrink-0 items-center border-b border-border px-4 sm:px-6">
        <Link
          href="/dashboard"
          className="flex items-center gap-2 rounded-sm text-sm font-medium text-primary"
        >
          <Logo size={16} />
          <span>SyncStudy</span>
        </Link>
      </header>

      <main className="flex flex-1 items-center justify-center px-4 py-16">
        <div className="w-full max-w-[420px]">
          <Card className="flex flex-col items-center gap-4 p-6 text-center">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-border-strong text-tertiary">
              <SearchX size={16} strokeWidth={1.5} aria-hidden="true" />
            </span>

            <div className="flex flex-col gap-1">
              <h1 className="text-base font-medium text-primary">No room with that code</h1>
              <p className="text-13 text-secondary">
                Room codes are {ROOM_CODE_LENGTH} characters and never contain 0, 1, I, L, O or U.
                Check the link with whoever invited you — a host can also regenerate a code, which
                retires the old one immediately.
              </p>
            </div>

            <div className="mt-1 flex flex-wrap items-center justify-center gap-2">
              <Link href="/join" className={buttonVariants({ variant: 'primary' })}>
                Enter a code
              </Link>
              <Link href="/dashboard" className={buttonVariants({ variant: 'secondary' })}>
                Your rooms
              </Link>
            </div>
          </Card>
        </div>
      </main>
    </div>
  );
}
